In [3]:
#operasi matriks

import numpy as np
A = np.array([[80, 30, 25],
              [50, 20, 10]])
B = np.array([[30, 60, 15],
              [10, 30, 30]])

hasil = A + B
print(hasil)

[[110  90  40]
 [ 60  50  40]]


In [ ]:
# operasi dot product 

import numpy as np
A = np.array([10, 20, 15, 20])
# A = [A1, A2, A3, A4]
B = np.array([16, 67, 35, 15])
# B = [B1, B2, B3, B4]

hasil = np.dot(A, B)
# hasil = (A1 X B1) + (A2 X B2) + (A3 X B3) + (A4 X B4)
print(hasil)

2325


In [ ]:
#operasi cross product 

import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)
print(Hasil)

[-305 -110  350]
