In [14]:
import numpy as np

A = np.array ([[3, 1],
              [2, 0]])

B = np.array ([[2, 1],
              [1, -1]])

C = np.array([[-1, 1, 2],
             [2, 0, -1]])

hasil = np.dot(A, B)
Hasil = np.dot(B, C)

print("A. A x B:\n", hasil, "\n")
print("B. B x C:\n", Hasil)

A. A x B:
 [[7 2]
 [4 2]] 

B. B x C:
 [[ 0  2  3]
 [-3  1  3]]


In [11]:
import math

f_6 = math.factorial(6)
f_5 = math.factorial(5)
f_8 = math.factorial(8)

hasil = f_8 / f_5

print("a. 6!: ", f_6, "\n")
print("b. 8! / 5!: ", hasil)

a. 6!:  720 

b. 8! / 5!:  336.0


In [13]:
import numpy as np


A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

DOT = np.dot(A, B)
CROSS = np.cross(A, B)

print("vektor A =", round(panjang_A, 2))
print("vektor B =", round(panjang_B, 2))
print("A . B =", DOT)
print("A x B =", CROSS)


vektor A = 9.11
vektor B = 12.41
A . B = 58
A x B = [ 24  79 -51]
